//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTimer.Core.Resx.strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res_str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res_str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LapTimer.Core.Resx.strings.res_str", typeof(res_str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose route.
        /// </summary>
        public static string CHOOSEROUTE {
            get {
                return ResourceManager.GetString("CHOOSEROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditions.
        /// </summary>
        public static string CONDITIONS {
            get {
                return ResourceManager.GetString("CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driveIn.
        /// </summary>
        public static string DRIVEIN {
            get {
                return ResourceManager.GetString("DRIVEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dry.
        /// </summary>
        public static string DRY {
            get {
                return ResourceManager.GetString("DRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        public static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Ride.
        /// </summary>
        public static string FREE_RIDE {
            get {
                return ResourceManager.GetString("FREE_RIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ground.
        /// </summary>
        public static string GROUND {
            get {
                return ResourceManager.GetString("GROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lap.
        /// </summary>
        public static string LAP {
            get {
                return ResourceManager.GetString("LAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ride.
        /// </summary>
        public static string RIDE {
            get {
                return ResourceManager.GetString("RIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rides.
        /// </summary>
        public static string RIDES {
            get {
                return ResourceManager.GetString("RIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routes.
        /// </summary>
        public static string ROUTES {
            get {
                return ResourceManager.GetString("ROUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slippery.
        /// </summary>
        public static string SLIPPERY {
            get {
                return ResourceManager.GetString("SLIPPERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        public static string TEMP {
            get {
                return ResourceManager.GetString("TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (hrs).
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total time.
        /// </summary>
        public static string TOTALTIME {
            get {
                return ResourceManager.GetString("TOTALTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string TRACK {
            get {
                return ResourceManager.GetString("TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet.
        /// </summary>
        public static string WET {
            get {
                return ResourceManager.GetString("WET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
