// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210321192829_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Data.Models.ConditionModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Clouds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Precipation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RideId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Wind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RideId")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Data.Models.GroundModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grounds");
                });

            modelBuilder.Entity("Data.Models.LapModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("RideId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("Data.Models.RideModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroundId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteEnum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroundId")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("Data.Models.RouteModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Data.Models.TrackpointModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LapModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("RouteModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LapModelId");

                    b.HasIndex("RouteModelId");

                    b.ToTable("Trackpoints");
                });

            modelBuilder.Entity("Data.Models.ConditionModel", b =>
                {
                    b.HasOne("Data.Models.RideModel", "Ride")
                        .WithOne("Condition")
                        .HasForeignKey("Data.Models.ConditionModel", "RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("Data.Models.LapModel", b =>
                {
                    b.HasOne("Data.Models.RideModel", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("Data.Models.RideModel", b =>
                {
                    b.HasOne("Data.Models.GroundModel", "Ground")
                        .WithOne("Ride")
                        .HasForeignKey("Data.Models.RideModel", "GroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.RouteModel", "Route")
                        .WithMany("Rides")
                        .HasForeignKey("RouteId");

                    b.Navigation("Ground");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Data.Models.TrackpointModel", b =>
                {
                    b.HasOne("Data.Models.LapModel", null)
                        .WithMany("Trackpoints")
                        .HasForeignKey("LapModelId");

                    b.HasOne("Data.Models.RouteModel", null)
                        .WithMany("Trackpoints")
                        .HasForeignKey("RouteModelId");
                });

            modelBuilder.Entity("Data.Models.GroundModel", b =>
                {
                    b.Navigation("Ride");
                });

            modelBuilder.Entity("Data.Models.LapModel", b =>
                {
                    b.Navigation("Trackpoints");
                });

            modelBuilder.Entity("Data.Models.RideModel", b =>
                {
                    b.Navigation("Condition");
                });

            modelBuilder.Entity("Data.Models.RouteModel", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("Trackpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
