//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTimer.Forms.UI.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LapTimer.Forms.UI.Resx.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No acces to GPS.
        /// </summary>
        public static string ERR_LOCATION {
            get {
                return ResourceManager.GetString("ERR_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive to the end of the.
        /// </summary>
        public static string INS_DRIVETOEND {
            get {
                return ResourceManager.GetString("INS_DRIVETOEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive to the start of the.
        /// </summary>
        public static string INS_DRIVETOSTART {
            get {
                return ResourceManager.GetString("INS_DRIVETOSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take up the starting position.
        /// </summary>
        public static string INS_PREPARESTART {
            get {
                return ResourceManager.GetString("INS_PREPARESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the entry?.
        /// </summary>
        public static string QES_DELETE {
            get {
                return ResourceManager.GetString("QES_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose route.
        /// </summary>
        public static string STR_CHOOSEROUTE {
            get {
                return ResourceManager.GetString("STR_CHOOSEROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conditions.
        /// </summary>
        public static string STR_CONDITIONS {
            get {
                return ResourceManager.GetString("STR_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driveIn.
        /// </summary>
        public static string STR_DRIVEIN {
            get {
                return ResourceManager.GetString("STR_DRIVEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dry.
        /// </summary>
        public static string STR_DRY {
            get {
                return ResourceManager.GetString("STR_DRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string STR_DURATION {
            get {
                return ResourceManager.GetString("STR_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        public static string STR_END {
            get {
                return ResourceManager.GetString("STR_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ground.
        /// </summary>
        public static string STR_GROUND {
            get {
                return ResourceManager.GetString("STR_GROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lap.
        /// </summary>
        public static string STR_LAP {
            get {
                return ResourceManager.GetString("STR_LAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string STR_LOAD {
            get {
                return ResourceManager.GetString("STR_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string STR_NAME {
            get {
                return ResourceManager.GetString("STR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string STR_NO {
            get {
                return ResourceManager.GetString("STR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ride.
        /// </summary>
        public static string STR_RIDE {
            get {
                return ResourceManager.GetString("STR_RIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rides.
        /// </summary>
        public static string STR_RIDES {
            get {
                return ResourceManager.GetString("STR_RIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routes.
        /// </summary>
        public static string STR_ROUTES {
            get {
                return ResourceManager.GetString("STR_ROUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string STR_SETTINGS {
            get {
                return ResourceManager.GetString("STR_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slippery.
        /// </summary>
        public static string STR_SLIPPERY {
            get {
                return ResourceManager.GetString("STR_SLIPPERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string STR_START {
            get {
                return ResourceManager.GetString("STR_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        public static string STR_TEMP {
            get {
                return ResourceManager.GetString("STR_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total time.
        /// </summary>
        public static string STR_TOTALTIME {
            get {
                return ResourceManager.GetString("STR_TOTALTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string STR_TRACK {
            get {
                return ResourceManager.GetString("STR_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet.
        /// </summary>
        public static string STR_WET {
            get {
                return ResourceManager.GetString("STR_WET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string STR_YES {
            get {
                return ResourceManager.GetString("STR_YES", resourceCulture);
            }
        }
    }
}
